### PR TITLE
Test MBEDTLS_CTR_DRBG_USE_128_BIT_KEY

### LINKED ISSUE #289: MBEDTLS_CTR_DRBG_USE_128_BIT_KEY is not tested
### Description

`MBEDTLS_CTR_DRBG_USE_128_BIT_KEY` is not tested on our CI. Since it's in the "Module configuration options" section of `config.h`, `config.pl full` does not set it. It isn't in any reference configuration in `configs` and isn't enabled by any component of `all.sh`.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

### LINKED ISSUE #290: The selftest program fails with MBEDTLS_CTR_DRBG_USE_128_BIT_KEY
### Description

Steps to reproduce:
```
scripts/config.pl set MBEDTLS_CTR_DRBG_USE_128_BIT_KEY
make
programs/test/selftest ctr_drbg
```

Expected behavior: `passed`

Actual behavior: `failed`

Reason for the failure: we only have test data with AES-256, not with AES-128.

Reasons this was not detected before:
* We normally run self-tests as part of the test suite, but the test case in `test_suite_ctr_drbg.data` has `depends_on:!MBEDTLS_CTR_DRBG_USE_128_BIT_KEY`, so the selftest is skipped when using AES-128. No such skipping happens in the selftest program.
* Even if we did run the selftests from the test suite, we don't actually enable `MBEDTLS_CTR_DRBG_USE_128_BIT_KEY` anywhere in `all.sh` (https://github.com/ARMmbed/mbed-crypto/issues/289).

How I detected this: in https://github.com/ARMmbed/mbed-crypto/pull/287 I moved `MBEDTLS_CTR_DRBG_USE_128_BIT_KEY` to the `mbed TLS feature support` section where it belongs, so it got picked up by `config.pl full`. We do run `selftest` in that configuration on the CI, albeit only on Windows.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [ ] Bug

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Test `MBEDTLS_CTR_DRBG_USE_128_BIT_KEY` properly. Fix #289. Fix #290.

Follow-up of #287.

Needs backports: to 2.16 (almost identical); to 2.7 (only for the `config.h` and `all.sh` changes that are about `MBEDTLS_ENTROPY_FORCE_SHA256`).

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
New Jenkins run: https://jenkins-internal.mbed.com/job/mbed-crypto-pr/job/PR-291-merge/12/

**Comment by gilles-peskine-arm** [comment]
I'll rebase again :(

**Comment by gilles-peskine-arm** [comment]
Rebased. Previous version in https://github.com/gilles-peskine-arm/mbed-crypto/tree/ctr_drbg-test_aes_128-2

File: library/ctr_drbg.c [hunk 1]
```diff
@@ -712,13 +712,23 @@ static const unsigned char nonce_pers_nopr[16] =
...
 
+#if defined(MBEDTLS_CTR_DRBG_USE_128_BIT_KEY)
+static const unsigned char result_pr[16] =
+    { 0x95, 0x3c, 0xa5, 0xbd, 0x44, 0x1, 0x34, 0xb7,
+      0x13, 0x58, 0x3e, 0x6a, 0x6c, 0x7e, 0x88, 0x8a };
+
+static const unsigned char result_nopr[16] =
+    { 0x6c, 0x25, 0x27, 0x95, 0xa3, 0x62, 0xd6, 0xdb,
+      0x90, 0xfd, 0x69, 0xb5, 0x42, 0x9, 0x4b, 0x84 };
+#else /* MBEDTLS_CTR_DRBG_USE_128_BIT_KEY */
```
Comment (piotr-now) [inline library/ctr_drbg.c]: Don't you think it would be more readable if there was added one extra line before and one after #else? Just as in the line 681?
